"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Person = {
  id: number; firstName: string; lastName: string; birthYear: number | null; deathYear: number | null;
  generation: number; branch: string; relation: string; description: string; story: string;
  traits: string; healthNotes: string; healthPrivate: number; photoKey: string | null;
};

const demo: Person[] = [
  {id:1,firstName:"Стоян",lastName:"Милев",birthYear:1889,deathYear:1967,generation:0,branch:"Милеви",relation:"прапрадядо",description:"Земеделец и разказвач на семейни истории.",story:"Пазел писмата на семейството в стар дървен сандък.",traits:"упоритост,майсторлък",healthNotes:"високо кръвно",healthPrivate:1,photoKey:null},
  {id:2,firstName:"Рада",lastName:"Милева",birthYear:1894,deathYear:1973,generation:0,branch:"Милеви",relation:"прапрабаба",description:"Събирала цялото семейство на празници.",story:"Рецептата ѝ за зелник още се предава между поколенията.",traits:"гостоприемство,градинарство",healthNotes:"диабет тип 2",healthPrivate:1,photoKey:null},
  {id:3,firstName:"Мария",lastName:"Петрова",birthYear:1928,deathYear:2014,generation:1,branch:"Петрови",relation:"прабаба",description:"Учителка с любов към книгите.",story:"Научила три поколения деца да четат.",traits:"любознателност,музика",healthNotes:"",healthPrivate:1,photoKey:null},
  {id:4,firstName:"Георги",lastName:"Петров",birthYear:1925,deathYear:2002,generation:1,branch:"Петрови",relation:"прадядо",description:"Дърводелец и тих майстор.",story:"Направил семейната маса, около която и днес се събираме.",traits:"майсторлък,спокойствие",healthNotes:"сърдечно заболяване",healthPrivate:1,photoKey:null},
  {id:5,firstName:"Елена",lastName:"Николова",birthYear:1932,deathYear:2021,generation:1,branch:"Николови",relation:"прабаба",description:"Пазител на снимки и документи.",story:"Надписвала всяка снимка с дата, място и имена.",traits:"памет,ред",healthNotes:"артрит",healthPrivate:1,photoKey:null},
  {id:6,firstName:"Димитър",lastName:"Николов",birthYear:1929,deathYear:1999,generation:1,branch:"Николови",relation:"прадядо",description:"Обичал планината и дългите разходки.",story:"Показал на внуците си всички пътеки около селото.",traits:"смелост,природа",healthNotes:"",healthPrivate:1,photoKey:null},
  {id:7,firstName:"Анна",lastName:"Петрова",birthYear:1951,deathYear:null,generation:2,branch:"Петрови",relation:"баба · майчина линия",description:"Събира семейните рецепти и спомени.",story:"Започнала първата тетрадка с родови истории.",traits:"грижа,кулинария",healthNotes:"алергия към пеницилин",healthPrivate:1,photoKey:null},
  {id:8,firstName:"Иван",lastName:"Петров",birthYear:1948,deathYear:2020,generation:2,branch:"Петрови",relation:"дядо · майчина линия",description:"Инженер и любител фотограф.",story:"Оставил стотици семейни негативи за дигитализиране.",traits:"фотография,изобретателност",healthNotes:"високо кръвно",healthPrivate:1,photoKey:null},
  {id:9,firstName:"Катя",lastName:"Милева",birthYear:1975,deathYear:null,generation:3,branch:"Милеви",relation:"дъщеря",description:"Свързва по-възрастните и младите в рода.",story:"Организира ежегодната семейна среща.",traits:"организираност,топлота",healthNotes:"",healthPrivate:1,photoKey:null},
  {id:10,firstName:"Николай",lastName:"Милев",birthYear:1972,deathYear:null,generation:3,branch:"Милеви",relation:"син",description:"Пази семейните документи.",story:"Открил актове за раждане от началото на XX век.",traits:"история,постоянство",healthNotes:"",healthPrivate:1,photoKey:null},
];

const genNames = ["I поколение · най-старо записано","II поколение","III поколение","IV поколение","V поколение","VI поколение"];
const tone = ["sage","amber","rose","blue"];
const initials = (p: Person) => `${p.firstName[0] ?? ""}${p.lastName[0] ?? ""}`;
const years = (p: Person) => p.birthYear && p.deathYear ? `${p.birthYear} – ${p.deathYear}` : p.birthYear ? String(p.birthYear) : p.deathYear ? `† ${p.deathYear}` : "";

export default function FamilyApp() {
  const [people,setPeople]=useState<Person[]>(demo), [view,setView]=useState("tree"), [query,setQuery]=useState("");
  const [selected,setSelected]=useState<Person|null>(null), [adding,setAdding]=useState(false), [busy,setBusy]=useState(false);
  const [zoom,setZoom]=useState(85), [notice,setNotice]=useState("");
  useEffect(()=>{fetch("/api/people").then(r=>r.ok?r.json():Promise.reject()).then(d=>d.people?.length&&setPeople(d.people)).catch(()=>{})},[]);
  const filtered=useMemo(()=>people.filter(p=>`${p.firstName} ${p.lastName} ${p.branch} ${p.traits}`.toLowerCase().includes(query.toLowerCase())),[people,query]);
  const generations=useMemo(()=>Array.from(new Set(filtered.map(p=>p.generation))).sort((a,b)=>a-b),[filtered]);
  const stories=people.filter(p=>p.story);
  async function addPerson(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());try{const response=await fetch("/api/people",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error();const data=await response.json();const photo=form.get("photo");if(photo instanceof File&&photo.size){const upload=new FormData();upload.set("personId",String(data.person.id));upload.set("photo",photo);const uploaded=await fetch("/api/photos",{method:"POST",body:upload});if(uploaded.ok)data.person.photoKey=(await uploaded.json()).photoKey}setPeople(v=>[...v,data.person]);setAdding(false);setNotice("Човекът е добавен към семейната памет.");setTimeout(()=>setNotice(""),3500)}catch{setNotice("Не успяхме да запазим. Опитай отново.")}finally{setBusy(false)}}
  return <main>
    <header className="topbar"><button className="brand brandButton" onClick={()=>setView("tree")} aria-label="Корени — начало"><span className="brandMark">К</span><span><strong>Корени</strong><small>семейна памет</small></span></button><nav aria-label="Основна навигация">{[["tree","Дърво"],["people","Хора"],["stories","Истории"],["health","Здраве"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav><button className="addButton" onClick={()=>setAdding(true)}>＋ Добави човек</button></header>
    <section className="hero"><div><p className="eyebrow">Семейство Милеви · {Math.max(...people.map(p=>p.generation))+1} поколения</p><h1>Историята ни няма<br/><em>един център.</em></h1><p className="intro">Всеки човек е част от картината. Разглеждай рода по линии, поколения и връзки — от най-старите спомени до днес.</p></div><div className="heroStats"><div><strong>{people.length}</strong><span>човека</span></div><div><strong>{Math.max(...people.map(p=>p.generation))+1}</strong><span>поколения</span></div><div><strong>{stories.length}</strong><span>истории</span></div></div></section>
    <section className="workspace">
      <div className="workspaceHead"><div className="viewSwitch">{[["tree","Родово дърво"],["people","Всички хора"],["stories","Истории"],["health","Здравна памет"]].map(([id,label])=><button key={id} className={view===id?"selected":""} onClick={()=>setView(id)}>{label}</button>)}</div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Търси име, род или черта…"/></label>{view==="tree"&&<div className="tools"><button onClick={()=>setZoom(z=>Math.max(55,z-10))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(120,z+10))}>＋</button><button className="fit" onClick={()=>setZoom(85)}>Побери</button></div>}</div>
      {view==="tree"&&<div className="treeViewport"><div className="familyTree" style={{transform:`scale(${zoom/100})`}}>{generations.map(g=><section className="generation" key={g}><div className="generationLabel">{genNames[g]||`Поколение ${g+1}`}</div><div className="generationLine">{filtered.filter(p=>p.generation===g).map((p,i)=><PersonCard key={p.id} person={p} index={i} onOpen={()=>setSelected(p)}/>)}</div></section>)}</div></div>}
      {view==="people"&&<div className="peopleGrid">{filtered.map((p,i)=><PersonCard key={p.id} person={p} index={i} onOpen={()=>setSelected(p)}/>)}</div>}
      {view==="stories"&&<div className="storyGrid">{stories.filter(p=>`${p.firstName} ${p.lastName} ${p.story}`.toLowerCase().includes(query.toLowerCase())).map((p,i)=><article className="storyCard" key={p.id}><div className={`avatar ${tone[i%4]}`}>{initials(p)}</div><p>„{p.story}“</p><button onClick={()=>setSelected(p)}>{p.firstName} {p.lastName} · {p.branch} →</button></article>)}</div>}
      {view==="health"&&<HealthView people={filtered} onOpen={setSelected}/>} 
    </section>
    <aside className="privacyNote"><span className="lock">●</span><div><strong>Семейното здраве остава семейно</strong><p>Здравните бележки са отделени от историите и са видими само в защитеното семейно пространство.</p></div><button onClick={()=>setView("health")}>Прегледай →</button></aside>
    {selected&&<Profile person={selected} onClose={()=>setSelected(null)}/>} {adding&&<AddModal onClose={()=>setAdding(false)} onSubmit={addPerson} busy={busy}/>} {notice&&<div className="toast" role="status">{notice}</div>}
  </main>
}

function PersonCard({person,index,onOpen}:{person:Person,index:number,onOpen:()=>void}){const life=years(person);return <button className="personCard" onClick={onOpen}><Photo person={person} className={`avatar ${tone[index%4]}`}/><div><h2>{person.firstName} {person.lastName}</h2>{life&&<p>{life}</p>}<span>{person.branch||"семейна линия"}</span></div><b aria-hidden>→</b></button>}
function Photo({person,className}:{person:Person,className:string}){return person.photoKey?<img className={className} src={`/api/photos?key=${encodeURIComponent(person.photoKey)}`} alt=""/>:<div className={className}>{initials(person)}</div>}
function Profile({person,onClose}:{person:Person,onClose:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer" role="dialog" aria-modal="true" aria-label={`Профил на ${person.firstName}`}><button className="close" onClick={onClose}>×</button><div className="profileHero"><Photo person={person} className="profilePhoto"/><p className="eyebrow">{person.branch||"семейна линия"}</p><h2>{person.firstName} {person.lastName}</h2><span>{years(person)}</span></div><section><h3>За човека и връзките</h3><p>{person.description||"Тук семейството може да добави описание и връзки с други хора."}</p></section><section><h3>Семейна история</h3><blockquote>{person.story?`„${person.story}“`:"Все още няма добавена история."}</blockquote></section><section><h3>Характер и наследство</h3><div className="chips">{person.traits?person.traits.split(",").map(x=><span key={x}>{x.trim()}</span>):<em>Няма добавени черти</em>}</div></section><section className="healthBox"><div><small>ЗАЩИТЕНА БЕЛЕЖКА</small><h3>Здравна памет</h3></div><p>{person.healthNotes||"Няма добавени здравни особености."}</p><i>Това не е медицинска диагноза. Споделяйте само с изрично съгласие.</i></section></aside></div>}
function HealthView({people,onOpen}:{people:Person[],onOpen:(p:Person)=>void}){const noted=people.filter(p=>p.healthNotes);return <div className="healthView"><div className="healthIntro"><span className="shield">●</span><div><p className="eyebrow">Защитено семейно пространство</p><h2>Здравна памет през поколенията</h2><p>Записвайте само потвърдени факти и семейни особености. Данните помагат за разговор с лекар, но не заменят медицинска консултация.</p></div></div><div className="healthList">{noted.length?noted.map(p=>{const life=years(p);return <button key={p.id} onClick={()=>onOpen(p)}><span>{p.firstName} {p.lastName}<small>{p.branch}{life?` · ${life}`:""}</small></span><strong>{p.healthNotes}</strong><b>→</b></button>}):<p className="empty">Няма здравни бележки за този избор.</p>}</div></div>}
function AddModal({onClose,onSubmit,busy}:{onClose:()=>void,onSubmit:(e:FormEvent<HTMLFormElement>)=>void,busy:boolean}){return <div className="overlay modalWrap"><form className="modal" onSubmit={onSubmit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">Нова семейна връзка</p><h2>Добави човек</h2><div className="formGrid"><label>Име<input name="firstName" required/></label><label>Фамилия<input name="lastName" required/></label><label>Година на раждане<input name="birthYear" type="number" min="1700" max="2100"/></label><label>Година на смъртта<input name="deathYear" type="number" min="1700" max="2100"/></label><label>Поколение<select name="generation" defaultValue="3">{genNames.map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label><label>Родова линия<input name="branch" placeholder="напр. Милеви"/></label><label className="wide">Описание и семейни връзки<textarea name="description" rows={3} placeholder="напр. Дъщеря на… Сестра на…"/></label><label className="wide">История<textarea name="story" rows={2}/></label><label className="wide">Черти и умения<input name="traits" placeholder="музика, майсторлък, смелост"/></label><label className="wide sensitive">Здравна бележка<textarea name="healthNotes" rows={2} placeholder="Само със съгласие на човека или семейството"/></label><label className="wide fileInput">Снимка<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></label></div><div className="formActions"><button type="button" onClick={onClose}>Отказ</button><button className="addButton" disabled={busy}>{busy?"Запазване…":"Добави към дървото"}</button></div></form></div>}
