"use client";

import { FormEvent, PointerEvent as ReactPointerEvent, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";

type Person = {
  id: number; firstName: string; lastName: string; birthYear: number | null; deathYear: number | null;
  generation: number; branch: string; relation: string; description: string; story: string;
  traits: string; healthNotes: string; healthPrivate: number; photoKey: string | null;
  customFields?: {label:string;value:string}[];
};
type Relationship = { id:number; personId:number; relatedPersonId:number; type:"parent"|"partner"; story?:string; eventLabel?:string; eventDate?:string; place?:string; sourceUrl?:string };

const demo: Person[] = [
  {id:1,firstName:"Стоян",lastName:"Милев",birthYear:1889,deathYear:1967,generation:0,branch:"Милеви",relation:"прапрадядо",description:"Земеделец и разказвач на семейни истории.",story:"Пазел писмата на семейството в стар дървен сандък.",traits:"упоритост,майсторлък",healthNotes:"високо кръвно",healthPrivate:1,photoKey:null},
  {id:2,firstName:"Рада",lastName:"Милева",birthYear:1894,deathYear:1973,generation:0,branch:"Милеви",relation:"прапрабаба",description:"Събирала цялото семейство на празници.",story:"Рецептата ѝ за зелник още се предава между поколенията.",traits:"гостоприемство,градинарство",healthNotes:"диабет тип 2",healthPrivate:1,photoKey:null},
  {id:3,firstName:"Мария",lastName:"Петрова",birthYear:1928,deathYear:2014,generation:1,branch:"Петрови",relation:"прабаба",description:"Учителка с любов към книгите.",story:"Научила три поколения деца да четат.",traits:"любознателност,музика",healthNotes:"",healthPrivate:1,photoKey:null},
  {id:4,firstName:"Георги",lastName:"Петров",birthYear:1925,deathYear:2002,generation:1,branch:"Петрови",relation:"прадядо",description:"Дърводелец и тих майстор.",story:"Направил семейната маса, около която и днес се събираме.",traits:"майсторлък,спокойствие",healthNotes:"сърдечно заболяване",healthPrivate:1,photoKey:null},
  {id:5,firstName:"Елена",lastName:"Николова",birthYear:1932,deathYear:2021,generation:1,branch:"Николови",relation:"прабаба",description:"Пазител на снимки и документи.",story:"Надписвала всяка снимка с дата, място и имена.",traits:"памет,ред",healthNotes:"артрит",healthPrivate:1,photoKey:null},
  {id:6,firstName:"Димитър",lastName:"Николов",birthYear:1929,deathYear:1999,generation:1,branch:"Николови",relation:"прадядо",description:"Обичал планината и дългите разходки.",story:"Показал на внуците си всички пътеки около селото.",traits:"смелост,природа",healthNotes:"",healthPrivate:1,photoKey:null},
  {id:7,firstName:"Анна",lastName:"Петрова",birthYear:1951,deathYear:null,generation:2,branch:"Петрови",relation:"баба · майчина линия",description:"Събира семейните рецепти и спомени.",story:"Започнала първата тетрадка с родови истории.",traits:"грижа,кулинария",healthNotes:"алергия към пеницилин",healthPrivate:1,photoKey:null},
  {id:8,firstName:"Иван",lastName:"Петров",birthYear:1948,deathYear:2020,generation:2,branch:"Петрови",relation:"дядо · майчина линия",description:"Инженер и любител фотограф.",story:"Оставил стотици семейни негативи за дигитализиране.",traits:"фотография,изобретателност",healthNotes:"високо кръвно",healthPrivate:1,photoKey:null},
  {id:9,firstName:"Катя",lastName:"Милева",birthYear:1975,deathYear:null,generation:3,branch:"Милеви",relation:"дъщеря",description:"Свързва по-възрастните и младите в рода.",story:"Организира ежегодната семейна среща.",traits:"организираност,топлота",healthNotes:"",healthPrivate:1,photoKey:null},
  {id:10,firstName:"Николай",lastName:"Милев",birthYear:1972,deathYear:null,generation:3,branch:"Милеви",relation:"син",description:"Пази семейните документи.",story:"Открил актове за раждане от началото на XX век.",traits:"история,постоянство",healthNotes:"",healthPrivate:1,photoKey:null},
];

const genNames = ["I поколение · най-старо записано","II поколение","III поколение","IV поколение","V поколение","VI поколение"];
const tone = ["sage","amber","rose","blue"];
const initials = (p: Person) => `${p.firstName[0] ?? ""}${p.lastName[0] ?? ""}`;
const years = (p: Person) => p.birthYear && p.deathYear ? `${p.birthYear} – ${p.deathYear}` : p.birthYear ? String(p.birthYear) : p.deathYear ? `† ${p.deathYear}` : "";
const api = (path:string) => typeof window!=="undefined"&&window.location.hostname.endsWith("github.io") ? `https://koreni-semeina-pamet.ivvmilev.chatgpt.site${path}` : path;
const branchColor = (branch:string) => {
  const family=branch.toLocaleLowerCase("bg");
  const isSpasovi=family.includes("спас"),isMilevi=family.includes("милев");
  if(isSpasovi&&isMilevi)return "#7656a5";
  if(isSpasovi)return "#197b72";
  if(isMilevi)return "#c06d22";
  return "#53745d";
};

export default function FamilyApp() {
  const [people,setPeople]=useState<Person[]>(demo), [view,setView]=useState("tree"), [query,setQuery]=useState("");
  const [relationships,setRelationships]=useState<Relationship[]>([]);
  const [selected,setSelected]=useState<Person|null>(null), [editing,setEditing]=useState<Person|null>(null), [editingRelationship,setEditingRelationship]=useState<Relationship|null>(null), [adding,setAdding]=useState(false), [busy,setBusy]=useState(false);
  const [zoom,setZoom]=useState(85), [pan,setPan]=useState({x:0,y:0}), [artMode,setArtMode]=useState<"living"|"calm">("living"), [notice,setNotice]=useState("");
  useEffect(()=>{fetch(api("/api/people")).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(d.people?.length)setPeople(d.people);setRelationships(d.relationships||[])}).catch(()=>{})},[]);
  const filtered=useMemo(()=>people.filter(p=>`${p.firstName} ${p.lastName} ${p.branch} ${p.traits}`.toLowerCase().includes(query.toLowerCase())),[people,query]);
  const generations=useMemo(()=>Array.from(new Set(filtered.map(p=>p.generation))).sort((a,b)=>a-b),[filtered]);
  const stories=people.filter(p=>p.story);
  const payloadFrom=(form:FormData)=>({...Object.fromEntries(form.entries()),customFields:form.getAll("customLabel").map((label,index)=>({label,value:form.getAll("customValue")[index]}))});
  async function addPerson(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const payload=payloadFrom(form);try{const response=await fetch(api("/api/people"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error();const data=await response.json();const photo=form.get("photo");if(photo instanceof File&&photo.size){const upload=new FormData();upload.set("personId",String(data.person.id));upload.set("photo",photo);const uploaded=await fetch(api("/api/photos"),{method:"POST",body:upload});if(uploaded.ok)data.person.photoKey=(await uploaded.json()).photoKey}const links:[[string,"parent"|"partner"]]=[["parent1","parent"]] as [[string,"parent"|"partner"]];links.push(["parent2","parent"],["partner","partner"]);for(const [field,type] of links){const related=Number(form.get(field));if(related)await fetch(api("/api/relationships"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(type==="parent"?{personId:related,relatedPersonId:data.person.id,type}:{personId:data.person.id,relatedPersonId:related,type})})}const refreshed=await fetch(api("/api/people")).then(r=>r.json());setPeople(refreshed.people);setRelationships(refreshed.relationships||[]);setAdding(false);setNotice("Човекът и семейните връзки са добавени.");setTimeout(()=>setNotice(""),3500)}catch{setNotice("Не успяхме да запазим. Опитай отново.")}finally{setBusy(false)}}
  async function editPerson(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setBusy(true);const form=new FormData(event.currentTarget);try{const response=await fetch(api("/api/people"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...payloadFrom(form),id:editing.id})});if(!response.ok)throw new Error();const photo=form.get("photo");if(photo instanceof File&&photo.size){const upload=new FormData();upload.set("personId",String(editing.id));upload.set("photo",photo);await fetch(api("/api/photos"),{method:"POST",body:upload})}const refreshed=await fetch(api("/api/people")).then(r=>r.json());setPeople(refreshed.people);setRelationships(refreshed.relationships||[]);setEditing(null);setNotice("Промените са запазени.");setTimeout(()=>setNotice(""),3500)}catch{setNotice("Не успяхме да запазим промените.")}finally{setBusy(false)}}
  async function editRelationship(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editingRelationship)return;setBusy(true);const form=new FormData(event.currentTarget);try{const response=await fetch(api("/api/relationships"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(form.entries()),id:editingRelationship.id})});if(!response.ok)throw new Error();const refreshed=await fetch(api("/api/people")).then(r=>r.json());setPeople(refreshed.people);setRelationships(refreshed.relationships||[]);setEditingRelationship(null);setNotice("Историята на връзката е запазена.");setTimeout(()=>setNotice(""),3500)}catch{setNotice("Не успяхме да запазим историята.")}finally{setBusy(false)}}
  return <main>
    <header className="topbar"><button className="brand brandButton" onClick={()=>setView("tree")} aria-label="Корени — начало"><span className="brandMark">К</span><span><strong>Корени</strong><small>семейна памет</small></span></button><nav aria-label="Основна навигация">{[["tree","Дърво"],["people","Хора"],["stories","Истории"],["health","Здраве"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav><button className="addButton" onClick={()=>setAdding(true)}>＋ Добави човек</button></header>
    <section className="hero"><div><p className="eyebrow">Семейство Милеви · {Math.max(...people.map(p=>p.generation))+1} поколения</p><h1>Историята ни няма<br/><em>един център.</em></h1><p className="intro">Всеки човек е част от картината. Разглеждай рода по линии, поколения и връзки — от най-старите спомени до днес.</p></div><div className="heroStats"><div><strong>{people.length}</strong><span>човека</span></div><div><strong>{Math.max(...people.map(p=>p.generation))+1}</strong><span>поколения</span></div><div><strong>{stories.length}</strong><span>истории</span></div></div></section>
    <section className="workspace">
      <div className="workspaceHead"><div className="viewSwitch">{[["tree","Родово дърво"],["people","Всички хора"],["stories","Истории"],["health","Здравна памет"]].map(([id,label])=><button key={id} className={view===id?"selected":""} onClick={()=>setView(id)}>{label}</button>)}</div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Търси име, род или черта…"/></label>{view==="tree"&&<><div className="artSwitch" aria-label="Стил на фона"><button className={artMode==="calm"?"active":""} onClick={()=>setArtMode("calm")}>Спокоен</button><button className={artMode==="living"?"active":""} onClick={()=>setArtMode("living")}>Жив</button></div><div className="tools"><button aria-label="Намали дървото" onClick={()=>setZoom(z=>Math.max(35,z-10))}>−</button><input aria-label="Мащаб на дървото" type="range" min="35" max="170" step="5" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><span>{zoom}%</span><button aria-label="Увеличи дървото" onClick={()=>setZoom(z=>Math.min(170,z+10))}>＋</button><button className="fit" onClick={()=>{setZoom(85);setPan({x:0,y:0})}}>Побери</button></div></>}</div>
      {view==="tree"&&<FamilyGraph people={filtered} relationships={relationships} generations={generations} zoom={zoom} pan={pan} setPan={setPan} artMode={artMode} onOpen={setSelected}/>}
      {view==="people"&&<div className="peopleGrid">{filtered.map((p,i)=><PersonCard key={p.id} person={p} index={i} onOpen={()=>setSelected(p)}/>)}</div>}
      {view==="stories"&&<div className="storyGrid">{stories.filter(p=>`${p.firstName} ${p.lastName} ${p.story}`.toLowerCase().includes(query.toLowerCase())).map((p,i)=><article className="storyCard" key={p.id}><div className={`avatar ${tone[i%4]}`}>{initials(p)}</div><p>„{p.story}“</p><button onClick={()=>setSelected(p)}>{p.firstName} {p.lastName} · {p.branch} →</button></article>)}</div>}
      {view==="health"&&<HealthView people={filtered} onOpen={setSelected}/>} 
    </section>
    <aside className="privacyNote"><span className="lock">●</span><div><strong>Семейното здраве остава семейно</strong><p>Здравните бележки са отделени от историите и са видими само в защитеното семейно пространство.</p></div><button onClick={()=>setView("health")}>Прегледай →</button></aside>
    {selected&&<Profile person={selected} people={people} relationships={relationships} onClose={()=>setSelected(null)} onEdit={()=>{setEditing(selected);setSelected(null)}} onEditRelationship={relationship=>{setEditingRelationship(relationship);setSelected(null)}}/>} {adding&&<AddModal people={people} onClose={()=>setAdding(false)} onSubmit={addPerson} busy={busy}/>} {editing&&<EditModal person={editing} onClose={()=>setEditing(null)} onSubmit={editPerson} busy={busy}/>} {editingRelationship&&<RelationshipModal relationship={editingRelationship} people={people} onClose={()=>setEditingRelationship(null)} onSubmit={editRelationship} busy={busy}/>} {notice&&<div className="toast" role="status">{notice}</div>}
  </main>
}

function PersonCard({person,index,onOpen}:{person:Person,index:number,onOpen:()=>void}){const life=years(person);return <button className="personCard" onClick={onOpen}><Photo person={person} className={`avatar ${tone[index%4]}`}/><div><h2>{person.firstName} {person.lastName}</h2>{life&&<p>{life}</p>}<span>{person.branch||"семейна линия"}</span></div><b aria-hidden>→</b></button>}

function FamilyGraph({people,relationships,generations,zoom,pan,setPan,artMode,onOpen}:{people:Person[];relationships:Relationship[];generations:number[];zoom:number;pan:{x:number;y:number};setPan:(pan:{x:number;y:number})=>void;artMode:"living"|"calm";onOpen:(p:Person)=>void}){
  const wrapRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),viewportRef=useRef<HTMLDivElement>(null),nodeRefs=useRef(new Map<number,HTMLDivElement>()),dragRef=useRef<{x:number;y:number;panX:number;panY:number;moved:boolean}|null>(null),suppressClickRef=useRef(false);
  const visibleIds=useMemo(()=>new Set(people.map(p=>p.id)),[people]);
  const visibleLinks=useMemo(()=>relationships.filter(r=>visibleIds.has(r.personId)&&visibleIds.has(r.relatedPersonId)),[relationships,visibleIds]);
  const orderedGroups=(generation:number)=>{const tier=people.filter(p=>p.generation===generation),seen=new Set<number>(),groups:Person[][]=[];for(const p of tier){if(seen.has(p.id))continue;const link=visibleLinks.find(r=>r.type==="partner"&&(r.personId===p.id||r.relatedPersonId===p.id));const partner=link&&tier.find(x=>x.id===(link.personId===p.id?link.relatedPersonId:link.personId));const group=partner?[p,partner]:[p];group.forEach(x=>seen.add(x.id));groups.push(group)}return groups};
  useLayoutEffect(()=>{const wrap=wrapRef.current,canvas=canvasRef.current;if(!wrap||!canvas)return;const draw=()=>{const rect=wrap.getBoundingClientRect(),scale=rect.width/wrap.offsetWidth||1,width=wrap.offsetWidth,height=wrap.offsetHeight,ratio=window.devicePixelRatio||1;canvas.width=width*ratio;canvas.height=height*ratio;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(ratio,ratio);ctx.clearRect(0,0,width,height);for(const link of visibleLinks){const a=nodeRefs.current.get(link.personId),b=nodeRefs.current.get(link.relatedPersonId);if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),source=people.find(p=>p.id===link.personId),color=link.type==="partner"?"#a64f67":branchColor(source?.branch||"");ctx.beginPath();ctx.lineWidth=link.type==="partner"?3.5:3;ctx.strokeStyle=color;ctx.setLineDash(link.type==="partner"?[8,5]:[]);if(link.type==="partner"){ctx.moveTo((ar.right-rect.left)/scale,(ar.top-rect.top+ar.height/2)/scale);ctx.lineTo((br.left-rect.left)/scale,(br.top-rect.top+br.height/2)/scale)}else{const x1=(ar.left-rect.left+ar.width/2)/scale,y1=(ar.bottom-rect.top)/scale,x2=(br.left-rect.left+br.width/2)/scale,y2=(br.top-rect.top)/scale,mid=y1+(y2-y1)*.52;ctx.moveTo(x1,y1);ctx.bezierCurveTo(x1,mid,x2,mid,x2,y2)}ctx.stroke()}};draw();const observer=new ResizeObserver(draw);observer.observe(wrap);window.addEventListener("resize",draw);return()=>{observer.disconnect();window.removeEventListener("resize",draw)}},[visibleLinks,people,zoom]);
  const startDrag=(event:ReactPointerEvent<HTMLDivElement>)=>{if(event.button!==0||(event.target as HTMLElement).closest("button,input,a"))return;dragRef.current={x:event.clientX,y:event.clientY,panX:pan.x,panY:pan.y,moved:false};viewportRef.current?.setPointerCapture(event.pointerId)};
  const moveDrag=(event:ReactPointerEvent<HTMLDivElement>)=>{const drag=dragRef.current;if(!drag)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(Math.abs(dx)>3||Math.abs(dy)>3)drag.moved=true;setPan({x:drag.panX+dx,y:drag.panY+dy})};
  const endDrag=()=>{if(dragRef.current?.moved)suppressClickRef.current=true;dragRef.current=null};
  return <div ref={viewportRef} className={`treeViewport ${artMode}`} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} onClickCapture={event=>{if(suppressClickRef.current){event.preventDefault();event.stopPropagation();suppressClickRef.current=false}}}><div className="treeScenery" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><div className="graphScale" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom/100})`}}><div className="familyGraph" ref={wrapRef}><canvas ref={canvasRef} aria-hidden="true"/><div className="graphTitle"><span>Родословни връзки</span><small className="linkLegend"><em className="spasovi"/>Спасови <em className="milevi"/>Милеви <em className="mixed"/>смесена линия <em className="partners"/>партньори</small></div>{generations.map(g=><section className="graphTier" key={g}><div className="generationLabel">{genNames[g]||`Поколение ${g+1}`}</div><div className="familyGroups">{orderedGroups(g).map((group,index)=><div className={`familyUnit ${group.length===2?"coupled":""}`} key={group.map(p=>p.id).join("-")}>{group.map((p,i)=><div className="graphNode" key={p.id} ref={el=>{if(el)nodeRefs.current.set(p.id,el);else nodeRefs.current.delete(p.id)}}><PersonCard person={p} index={index+i} onOpen={()=>onOpen(p)}/></div>)}</div>)}</div></section>)}</div></div></div>
}
function Photo({person,className}:{person:Person,className:string}){return person.photoKey?<img className={className} src={api(`/api/photos?key=${encodeURIComponent(person.photoKey)}`)} alt=""/>:<div className={className}>{initials(person)}</div>}
function RelationshipSection({person,people,relationships,onEdit}:{person:Person;people:Person[];relationships:Relationship[];onEdit:(relationship:Relationship)=>void}){const items=relationships.filter(r=>r.personId===person.id||r.relatedPersonId===person.id);return <section className="relationshipStories"><h3>Връзки и общи истории</h3>{items.length?items.map(relationship=>{const otherId=relationship.personId===person.id?relationship.relatedPersonId:relationship.personId,other=people.find(p=>p.id===otherId);if(!other)return null;const role=relationship.type==="partner"?"партньори":relationship.personId===person.id?"дете":"родител";return <button key={relationship.id} onClick={()=>onEdit(relationship)}><span><strong>{other.firstName} {other.lastName}</strong><small>{role}{relationship.eventLabel?` · ${relationship.eventLabel}`:""}{relationship.eventDate?` · ${relationship.eventDate}`:""}</small>{relationship.story&&<em>{relationship.story}</em>}</span><b>{relationship.story?"Редактирай":"＋ История"}</b></button>}):<p>Все още няма записани връзки.</p>}</section>}
// The backdrop intentionally closes the drawer on pointer interaction outside it.
// eslint-disable-next-line jsx-a11y/no-static-element-interactions
function Profile({person,people,relationships,onClose,onEdit,onEditRelationship}:{person:Person;people:Person[];relationships:Relationship[];onClose:()=>void;onEdit:()=>void;onEditRelationship:(relationship:Relationship)=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer" role="dialog" aria-modal="true" aria-label={`Профил на ${person.firstName}`}><button className="close" onClick={onClose}>×</button><div className="profileHero"><Photo person={person} className="profilePhoto"/><p className="eyebrow">{person.branch||"семейна линия"}</p><h2>{person.firstName} {person.lastName}</h2><span>{years(person)}</span><button className="editProfile" onClick={onEdit}>✎ Редактирай данните</button></div><section><h3>За човека</h3><p>{person.description||"Тук семейството може да добави описание за човека."}</p></section><section><h3>Семейна история</h3><blockquote>{person.story?`„${person.story}“`:"Все още няма добавена история."}</blockquote></section><RelationshipSection person={person} people={people} relationships={relationships} onEdit={onEditRelationship}/><section><h3>Характер и наследство</h3><div className="chips">{person.traits?person.traits.split(",").map(x=><span key={x}>{x.trim()}</span>):<em>Няма добавени черти</em>}</div></section>{!!person.customFields?.length&&<section><h3>Още за човека</h3><dl className="customDetails">{person.customFields.map((field,index)=><div key={`${field.label}-${index}`}><dt>{field.label}</dt><dd>{field.value}</dd></div>)}</dl></section>}<section className="healthBox"><div><small>ЗАЩИТЕНА БЕЛЕЖКА</small><h3>Здравна памет</h3></div><p>{person.healthNotes||"Няма добавени здравни особености."}</p><i>Това не е медицинска диагноза. Споделяйте само с изрично съгласие.</i></section></aside></div>}
function HealthView({people,onOpen}:{people:Person[],onOpen:(p:Person)=>void}){const noted=people.filter(p=>p.healthNotes);return <div className="healthView"><div className="healthIntro"><span className="shield">●</span><div><p className="eyebrow">Защитено семейно пространство</p><h2>Здравна памет през поколенията</h2><p>Записвайте само потвърдени факти и семейни особености. Данните помагат за разговор с лекар, но не заменят медицинска консултация.</p></div></div><div className="healthList">{noted.length?noted.map(p=>{const life=years(p);return <button key={p.id} onClick={()=>onOpen(p)}><span>{p.firstName} {p.lastName}<small>{p.branch}{life?` · ${life}`:""}</small></span><strong>{p.healthNotes}</strong><b>→</b></button>}):<p className="empty">Няма здравни бележки за този избор.</p>}</div></div>}
function CustomFieldsEditor({initial=[]}:{initial?:{label:string;value:string}[]}){const [fields,setFields]=useState(initial);return <fieldset className="customFields"><legend>Допълнителни полета</legend><p>Добави каквото е важно за този човек — например професия, родно място или образование.</p>{fields.map((field,index)=><div className="customFieldRow" key={index}><input name="customLabel" defaultValue={field.label} placeholder="Име на полето" aria-label={`Име на допълнително поле ${index+1}`}/><input name="customValue" defaultValue={field.value} placeholder="Стойност" aria-label={`Стойност на допълнително поле ${index+1}`}/><button type="button" onClick={()=>setFields(items=>items.filter((_,i)=>i!==index))} aria-label="Премахни полето">×</button></div>)}<button className="addField" type="button" onClick={()=>setFields(items=>[...items,{label:"",value:""}])}>＋ Добави свое поле</button></fieldset>}
function PersonFields({person}:{person?:Person}){return <><label>Име<input name="firstName" required defaultValue={person?.firstName}/></label><label>Фамилия<input name="lastName" required defaultValue={person?.lastName}/></label><label>Година на раждане<input name="birthYear" type="number" min="1700" max="2100" defaultValue={person?.birthYear||""}/></label><label>Година на смъртта<input name="deathYear" type="number" min="1700" max="2100" defaultValue={person?.deathYear||""}/></label><label>Поколение<select name="generation" defaultValue={person?.generation??3}>{genNames.map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label><label>Родова линия<input name="branch" placeholder="напр. Милеви" defaultValue={person?.branch}/></label><label className="wide">Описание<textarea name="description" rows={3} defaultValue={person?.description}/></label><label className="wide">История<textarea name="story" rows={2} defaultValue={person?.story}/></label><label className="wide">Черти и умения<input name="traits" placeholder="музика, майсторлък, смелост" defaultValue={person?.traits}/></label><label className="wide sensitive">Здравна бележка<textarea name="healthNotes" rows={2} placeholder="Само със съгласие на човека или семейството" defaultValue={person?.healthNotes}/></label></>}
function AddModal({people,onClose,onSubmit,busy}:{people:Person[];onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){const choices=<><option value="">— няма / неизвестен —</option>{people.map(p=><option value={p.id} key={p.id}>{p.firstName} {p.lastName} · {p.branch}</option>)}</>;return <div className="overlay modalWrap"><form className="modal" onSubmit={onSubmit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">Нова семейна връзка</p><h2>Добави човек</h2><div className="formGrid"><PersonFields/><label>Родител 1<select name="parent1">{choices}</select></label><label>Родител 2<select name="parent2">{choices}</select></label><label className="wide">Партньор<select name="partner">{choices}</select></label><CustomFieldsEditor/><label className="wide fileInput">Снимка<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></label></div><div className="formActions"><button type="button" onClick={onClose}>Отказ</button><button className="addButton" disabled={busy}>{busy?"Запазване…":"Добави към дървото"}</button></div></form></div>}
function EditModal({person,onClose,onSubmit,busy}:{person:Person;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <div className="overlay modalWrap"><form className="modal" onSubmit={onSubmit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">Профил в родословното дърво</p><h2>Редактирай {person.firstName}</h2><div className="formGrid"><PersonFields person={person}/><CustomFieldsEditor initial={person.customFields}/><label className="wide fileInput">Смени снимката<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></label></div><div className="formActions"><button type="button" onClick={onClose}>Отказ</button><button className="addButton" disabled={busy}>{busy?"Запазване…":"Запази промените"}</button></div></form></div>}
function RelationshipModal({relationship,people,onClose,onSubmit,busy}:{relationship:Relationship;people:Person[];onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){const first=people.find(p=>p.id===relationship.personId),second=people.find(p=>p.id===relationship.relatedPersonId);return <div className="overlay modalWrap"><form className="modal relationshipModal" onSubmit={onSubmit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">Обща семейна памет</p><h2>{first?.firstName} и {second?.firstName}</h2><p className="modalIntro">Запиши какво свързва тези двама души. Може да е история, важен момент или проверен семеен факт.</p><div className="formGrid"><label>Събитие<input name="eventLabel" defaultValue={relationship.eventLabel} placeholder="напр. Сватба или общ дом"/></label><label>Дата или период<input name="eventDate" defaultValue={relationship.eventDate} placeholder="напр. 1978 г."/></label><label className="wide">Място<input name="place" defaultValue={relationship.place} placeholder="град, село или държава"/></label><label className="wide">История на връзката<textarea name="story" rows={6} defaultValue={relationship.story} placeholder="Как са се запознали, какво са преживели заедно, семеен спомен…"/></label><label className="wide">Източник или документ<input name="sourceUrl" type="url" defaultValue={relationship.sourceUrl} placeholder="https://… (по желание)"/></label></div><div className="formActions"><button type="button" onClick={onClose}>Отказ</button><button className="addButton" disabled={busy}>{busy?"Запазване…":"Запази историята"}</button></div></form></div>}
