import { env } from "cloudflare:workers";

export const dynamic="force-dynamic";
type Platform={PHOTOS:R2Bucket;DB:D1Database};const platform=()=>env as unknown as Platform;
const headers={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
export const OPTIONS=()=>new Response(null,{status:204,headers});
const clean=(value:FormDataEntryValue|null,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
async function ensure(){await platform().DB.batch([platform().DB.prepare("CREATE TABLE IF NOT EXISTS family_media (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, person_id integer NOT NULL REFERENCES people(id) ON DELETE CASCADE, photo_key text NOT NULL, caption text DEFAULT '' NOT NULL, event_date text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)"),platform().DB.prepare("CREATE INDEX IF NOT EXISTS idx_family_media_person_date ON family_media (person_id, event_date)")])}
export async function GET(){try{await ensure();const result=await platform().DB.prepare("SELECT id, person_id as personId, photo_key as photoKey, caption, event_date as eventDate, created_at as createdAt FROM family_media ORDER BY event_date DESC, id DESC").all();return Response.json({memories:result.results},{headers:{...headers,"Cache-Control":"no-store"}})}catch{return Response.json({memories:[]},{status:500,headers})}}
export async function POST(request:Request){try{const data=await request.formData(),personId=Number(data.get("personId")),file=data.get("photo");if(!Number.isInteger(personId)||!(file instanceof File))return Response.json({error:"Липсва снимка или човек."},{status:400,headers});if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>8_000_000)return Response.json({error:"Използвай JPG, PNG или WEBP до 8 MB."},{status:400,headers});const ext=file.type.split("/")[1].replace("jpeg","jpg"),key=`albums/${personId}/${crypto.randomUUID()}.${ext}`;await platform().PHOTOS.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});await ensure();const caption=clean(data.get("caption"),500),eventDate=clean(data.get("eventDate"),40);const inserted=await platform().DB.prepare("INSERT INTO family_media (person_id, photo_key, caption, event_date) VALUES (?, ?, ?, ?) RETURNING id, person_id as personId, photo_key as photoKey, caption, event_date as eventDate, created_at as createdAt").bind(personId,key,caption,eventDate).first();return Response.json({memory:inserted},{status:201,headers})}catch(error){return Response.json({error:error instanceof Error?error.message:"Неуспешно качване"},{status:500,headers})}}
